name = "team_fireworks/maau"
version = "0.0.0"

[target]
environment = "lune"
lib = "init.luau"
bin = "main.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
argparse = { name = "caveful_games/argparse", version = "^0.1.2" }
chalk = { name = "kimpure/chalk_luau", version = "^0.1.7", target = "luau" }

[patches]
"caveful_games/argparse" = { "0.1.2 lune" = "patches/caveful_games+argparse-0.1.2+lune.patch" }
"kimpure/chalk_luau" = { "0.1.7 luau" = "patches/kimpure+chalk_luau-0.1.7+luau.patch" }
